### ISSUE TITLE
Forge’s Blockstates

### ISSUE THREAD

**Issue by loordgek** [Anime-Quatroctus/Blockstate-Generator#1]
can you make it can gen Forge’s Blockstates ??

**Comment by Quatroctus** [comment]
That is a planned feature, it would just take a little while to get the syntax correct :)

**Comment by loordgek** [comment]
https://gist.github.com/anonymous/a5f4cc01024e457e857a84610761c72e i have done it my self

**Comment by Quatroctus** [comment]
Awesome.

**Comment by loordgek** [comment]
you can have it :)

**Comment by Quatroctus** [comment]
Thank you. If you look at mine I clearly don't know how to use Gson. Or rather never used it prior.

**Comment by Quatroctus** [comment]
I have added your version of forge BlockState generator and revamped my vanilla generator.

**Comment by loordgek** [comment]
https://github.com/Anime-Quatroctus/Blockstate-Generator/blob/master/BlockStateGen/src/dev/anime/blockstate/generator/Generator.java#L165 maybe delete this i used it for testing

**Comment by Quatroctus** [comment]
I actually kinda liked it, this is only here to be used as a util after all. You cant use it to autogen during runtime so i thought why not keep it, plus it is a pain to delete the file for it to regen anyways.

**Comment by loordgek** [comment]
https://github.com/Anime-Quatroctus/Blockstate-Generator/blob/master/BlockStateGen/src/dev/anime/blockstate/generator/Generator.java#L159 put the "V1" after it since forge blockstate can be V1 V2 or V3 etc so the person who is going to use it can identify the version

**Comment by Quatroctus** [comment]
There isnt a V2 or V3 yet, so i don't need to put that yet. When and if there is i will update the generator to support those.
